### ISSUE TITLE
Break points or ranges for those attributes with Jenks bins values  

### ISSUE THREAD

**Issue by yinghuaguan** [OpenDRR/info-viz#24]
In our opinion, natural break classification is better to run in the backend because it’s a heavy lift job to do in the component. The app performance will be affected if we do it in the frontend.

**Comment by jvanulde** [comment]
@drotheram @wkhchow do you have any views on this?

**Comment by jvanulde** [comment]
Being looked at in https://github.com/OpenDRR/model-factory/issues/15
