### ISSUE TITLE
How to call components when embedding in the app? 

### ISSUE THREAD

**Issue by yinghuaguan** [OpenDRR/info-viz#25]
1. based on scenarios 
2. based on map and chart types 
3. ?  

Different ways will lead to different parameters to pass to the components.

**Comment by jvanulde** [comment]
We want to make it as flexible as possible. We are still in the process of finalizing the UX. I would suspect that the two you propose are good ones to start with. I've attached some preliminary concepts for the two interactions (hazard risk, earthquake risk). We can discuss further.
![Screen Shot 2020-03-18 at 3 06 33 PM](https://user-images.githubusercontent.com/2255248/77012006-542d0180-692a-11ea-90a9-2cafaa8f960e.png)
![Screen Shot 2020-03-18 at 3 06 19 PM](https://user-images.githubusercontent.com/2255248/77012017-598a4c00-692a-11ea-9d40-e56334f32fd2.png)

**Comment by jvanulde** [comment]
Closed. Documentation provided on April 2nd.
