### ISSUE TITLE
How to select which attributes to show on the map? 

### ISSUE THREAD

**Issue by yinghuaguan** [OpenDRR/info-viz#26]
I see GeoViewer uses layers to select which attribute to show, is it going to be the same behaviour in risk profiler?

**Comment by jvanulde** [comment]
@yinghuaguan do you mean if you click on a layer feature you see attributes?

**Comment by yinghuaguan** [comment]
![image](https://user-images.githubusercontent.com/32108918/77012004-52fbd480-692a-11ea-9f18-def006880003.png)
I mean like this. For example, for damage state scenario, there are multiple values need to show on map and chart, how do users select which value to show? @jvanulde

**Comment by jvanulde** [comment]
I believe that the UI will have controls (e.g. radio buttons, sliders) to control what attributes are shown.
![Screen Shot 2020-03-18 at 3 06 19 PM](https://user-images.githubusercontent.com/2255248/77012866-0a451b00-692c-11ea-9340-cea5636e3447.png)
